# Generated by Django 5.0.7 on 2024-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_chats_user_chathistory_chats_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chat_title',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
