# Generated by Django 5.0.7 on 2024-08-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_user_email_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
